js_task_fix_form_DOM: add tests
mate-academy/js_task_fix_form_DOM pull request #119
Opened 2020-11-20 13:27 UTC by brainwashers

2020-11-24 10:39 UTC, roman-mate requested changes

2020-11-24 10:39 UTC, roman-mate commented on cypress/integration/jsTaskFixFormDOM.spec.js
> +  });
https://docs.cypress.io/guides/references/best-practices.html#Setting-a-global-baseUrl

2020-11-24 10:39 UTC, roman-mate commented on cypress/integration/jsTaskFixFormDOM.spec.js
> +    cy.get(':nth-child(1) > :nth-child(1) > input').should('have.attr', 'placeholder');
is there a better css selector?

2020-11-24 10:39 UTC, roman-mate commented on cypress/integration/jsTaskFixFormDOM.spec.js
> +    cy.get(':nth-child(1) > :nth-child(1) > input').should('have.attr', 'placeholder');
same below.

2020-11-24 10:39 UTC, roman-mate commented on cypress/integration/jsTaskFixFormDOM.spec.js
> +    cy.get('form:nth-child(1) > :nth-child(1) > label').should('exist');
need better css selectors.

2020-11-24 10:39 UTC, roman-mate commented on cypress/integration/jsTaskFixFormDOM.spec.js
> +});
missing empty line

2020-11-30 12:11 UTC, roman-mate approved these changes

2020-11-30 12:11 UTC, roman-mate commented on cypress/integration/jsTaskFixFormDOM.spec.js
> +  it('should have abel for last name in sign up form', () => {
```suggestion
  it('should have label for last name in sign up form', () => {
```

2020-11-30 13:27 UTC, merged

2020-11-30 13:48 UTC, rhonyshniuk commented on cypress/integration/jsTaskFixFormDOM.spec.js
> +    cy.get('#sign-up-name').parent().children('label');
`cy.get('[for="sign-up-email"]')`

Change for all cases