js_task_fix_form_DOM
mate-academy/js_task_fix_form_DOM pull request #200
Opened 2021-03-03 15:36 UTC by SofiiaAsieieva

[DEMO LINK](https://SofiiaAsieieva.github.io/js_task_fix_form_DOM/)

2021-03-03 20:47 UTC, misha-lysak requested changes

2021-03-03 20:47 UTC, misha-lysak commented on src/scripts/main.js
> +  input.setAttribute('placeholder', capitalizeFirstLetter(input.name));
це також можна через крапку записати, буде навіть читабельніше

2021-03-03 20:47 UTC, misha-lysak commented on src/scripts/main.js
> +
що таке result?)

2021-03-03 21:22 UTC, misha-lysak approved these changes
![image](https://user-images.githubusercontent.com/63812444/109874032-41b0f280-7c77-11eb-9643-cd4365a6eec8.png)

2021-03-04 08:54 UTC, Vladimir-Beliy requested changes

2021-03-04 08:54 UTC, Vladimir-Beliy commented on src/scripts/main.js
> +  return modifiedString.charAt(0).toUpperCase() + modifiedString.slice(1);
```suggestion
  return modifiedString[0].toUpperCase() + modifiedString.slice(1);
```
почему charAt?

2021-03-04 09:08 UTC, Vladimir-Beliy approved these changes

2026-02-02 19:56 UTC, closed without merging