Fixed form
mate-academy/js_task_fix_form_DOM pull request #386
Opened 2022-04-08 23:10 UTC by OstTomash

2022-04-08 23:39 UTC, OstTomash commented
https://osttomash.github.io/js_task_fix_form_DOM/

2022-04-11 11:52 UTC, vkryvytskyy requested changes

2022-04-11 11:52 UTC, vkryvytskyy commented on README.md
> +    - [DEMO LINK](https://OstTomash.github.io/js_task_fix_form_DOM/)
<img width="591" alt="image" src="https://user-images.githubusercontent.com/38065883/162733850-ac37c1a5-23bb-4d1a-ad91-b050ebcde869.png">
Давай сделаем чтобы firstName и lastName были написаны раздельно

2022-04-11 13:18 UTC, ArturErmolenko approved these changes
Good job 👍

2023-11-09 16:32 UTC, closed without merging