done
mate-academy/js_task_fix_form_DOM pull request #66
Opened 2020-10-05 13:18 UTC by aionova

- [DEMO LINK](https://aionova.github.io/js_task_fix_form_DOM/)

2020-10-05 13:55 UTC, yazheviks approved these changes
Пушка!

2020-10-05 16:09 UTC, solaryasha requested changes

2020-10-05 16:09 UTC, solaryasha commented on src/scripts/main.js
> +  inputLabel.setAttribute('for', input.id);
```suggestion
  inputLabel.htmlFor = input.id
```

2020-10-05 16:09 UTC, solaryasha commented on src/scripts/main.js
> +  const placeholderText = input.name[0].toUpperCase() + input.name.slice(1);
Плейсхолдер через camelCase виглядає дивно. Зроби його у звичайному стилі

2020-10-06 11:36 UTC, solaryasha approved these changes
Well done !

2023-09-27 09:08 UTC, closed without merging