solution
mate-academy/js_task_fix_form_DOM pull request #75
Opened 2020-10-12 14:30 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/js_task_fix_form_DOM/)

2020-10-13 13:14 UTC, taniaomelko requested changes
Варто додати пробіл між словами для placeholder.

2020-10-13 13:14 UTC, taniaomelko commented on src/scripts/main.js
> +const inputs = [...document.querySelectorAll('.field-text')];
```suggestion
const inputs = document.querySelectorAll('.field-text');
```

2020-10-14 09:16 UTC, taniaomelko approved these changes

2020-10-15 09:15 UTC, danheim approved these changes
good

2026-01-18 11:51 UTC, closed without merging