done, sorry for vars names
mate-academy/js_task_fix_form_DOM pull request #761
Opened 2023-03-18 17:00 UTC by anton-chornobai

2023-03-19 08:32 UTC, etojeDenys requested changes
please, add Demo link to your PR

2023-03-19 09:14 UTC, anton-chornobai commented
[DEMO LINK](https://anton-chornobai.github.io/js_task_fix_form_DOM/)

2023-03-19 11:01 UTC, OleziO requested changes
Make inputs enable, not disable.

2023-03-19 11:01 UTC, OleziO commented on src/scripts/main.js
>  // write code here
Remove all comments from the code.

2023-04-20 14:02 UTC, anton-chornobai commented
demo -> https://anton-chornobai.github.io/js_task_fix_form_DOM/

2023-04-20 14:27 UTC, mykhalenych requested changes
Nice work, but change FIRSTNAME => FIRST NAME and LASTNAME => LAST NAME

2023-04-21 06:46 UTC, etojeDenys requested changes
still not fixed 
<img width="700" alt="image" src="https://user-images.githubusercontent.com/70220667/233561287-4342d40f-27f3-4789-9303-50d95c1bda4b.png">

2023-04-21 06:46 UTC, etojeDenys commented on src/scripts/main.js
> +function camelCaseCheck(s) {
Function names should be in camelCase. Rename `camelCaseCheck` to `checkCamelCase`.

2023-04-21 06:46 UTC, etojeDenys commented on src/scripts/main.js
> +const firstLetterCapitalizer = (s) => {
Function names should be in camelCase. Rename `firstLetterCapitalizer` to `capitalizeFirstLetter`.

2023-04-21 07:03 UTC, anton-chornobai commented on src/scripts/main.js
> +const firstLetterCapitalizer = (s) => {
Sorry its probably old deploy

2023-04-21 07:05 UTC, anton-chornobai commented
demo = https://anton-chornobai.github.io/js_task_fix_form_DOM/

2023-04-21 07:27 UTC, OleziO requested changes
Remove all unnecessary files from PR.

2023-04-21 07:27 UTC, OleziO commented on src/scripts/main.js
> +function checkCamelCase(s) {
Rename to `formatCamelCase`

2023-04-22 06:18 UTC, YegorKorenkov requested changes
Nice work, one minor mistake, in labels, words must also be separated by a space
![image](https://user-images.githubusercontent.com/54936044/233766456-614c833a-d60f-42e5-ade0-54e6601822d2.png)

2023-04-22 07:53 UTC, closed without merging