task complete
mate-academy/js_task_fix_form_DOM pull request #994
Opened 2024-04-18 07:44 UTC by Manankin

[DEMO LINK](https://manankin.github.io/js_task_fix_form_DOM/)

2024-04-19 11:49 UTC, olya-shyian requested changes
Great work!

2024-04-19 11:49 UTC, olya-shyian commented on src/scripts/main.js
> +function capitalizeString(str) {
can we write this function shorter? like

 str.slice(0, 1).toUpperCase() + str.slice(1),

2024-04-19 11:49 UTC, olya-shyian commented on src/scripts/main.js
> +  const capitalizeStr = str.split('').reduce((acc, char, index) => {
don't use 'str', 'func' etc. 
write full name please

2024-04-19 12:02 UTC, Manankin commented on src/scripts/main.js
> +function capitalizeString(str) {
Yes, it's easy. But in this case name='firstName' transform to "FirstName" instead of "First Name"
I have to capitalize name and split words - so every word from capital letter.

3) For each `input` set `placeholder` based on `input` name. Capitalize it.

2024-04-22 09:52 UTC, DanilWeda approved these changes
Great! 
Approved!

2024-07-16 11:25 UTC, closed without merging